export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const GET_COUNT = 'GET_COUNT';
export const INCREMENT_COUNT_BY_NUM = 'INCREMENT_COUNT_BY_NUM';